api.md, kubectl-for-docker.md
My first pull request. I changed the format of some words in order to improve the clarity of the documentation to the reader.
=> changing format to some words

Kubernetes_Architecture.md, pods101/deploy-your-first-nginx-pod.md
Adding a hyperlink associated with  Deployment 
Adding a hyperlink associated with  Pod 
Adding some dots to the end of some items
Adding sublevel to ClusterIP, Node Port, Load Balancer
=> adding some hyperlinks and subleveling some items

kube101.md
Fixed some typos and changed some fonts for easing the reading process.
=> fixing some typos

pods101/deploy-your-first-nginx-pod.md
I have added some apostrophes, link references and so on.
=> adding some tags/characters

Kubernetes_Architecture.md
change errors in spelling and wording
=> Kubernetes architecture spelling mistakes

helm/README.md
=> helm: created Readme.md for Helm!

replicaset101/README.md
Modified the README.md to put the spec related changes of ReplicaSet under a sub-point for clarity
=> Put replicaset spec under a sub point

dockerdesktopformac/argocd/README.md
Here's a quickstart guide to get started with ArgoCD on top of Docker Desktop 4.5.0
=> Added ArgoCD Tutorial for Docker Desktop

Helm101/chart-hooks.md, Helm101/chart-repos.md, Helm101/helm-charts.md, Helm101/installing-a-chart.md, Helm101/library-charts.md, Helm101/test-charts.md, Helm101/what-is-helm.md
Added guides for helm repo, charts development and testing
=> Finished Helm

AKS101/aks-keda.md, AKS101/aks-service-mesh.md, README.md
Finished AKS101 @collabnix please review and merge
=> Aks - Finished

weave-pwk.md
Hello, I noticed that a sentence in weave-pwk.md might be incorrectly placed in a code block. This PR fixes this typo.
=> Fix typo in weave-pwk.md

README.md
=> Added Security101 to homepage

Security101/kubernetes-security.md
=> Changes to Security lab

Deployment101/nginx-dep.yaml
I have changed replicas to 3 in nginx-dep.yaml
=> changed replicas to 3 in nginx-dep.yaml

namespace.yaml
I've added a namespace.yaml file
=> added a namespace.yaml file

pods101/deploy-your-first-nginx-pod.md
@ajeetraina  came across this while I was learning 😄
=> corrected spelling mistake

GitLab101/kubernetes-with-gitlab.md, GitLab101/runner-on-kubernetes.md, README.md
=> Git lab runner on Kubernetes

Logging101/kafka.md
=> Kafka fixes

kube101.md
Fixes: https://github.com/collabnix/kubelabs/issues/130
=> Added instruction to cd into kubelabs

201/monitoring/prometheus.md, DaemonSet101/README.md, DaemonSet101/daemonset.yml, Deployment101/blue-deploy.yaml, Deployment101/green-deploy.yaml, Deployment101/nginx-test.yml, replicaset101/README.md, secerts_configmaps101/secrets-configmaps.md
=> Fixed issue #112

Cheat Sheets/Helm Cheat Sheet.md, Cheat Sheets/Kubernetes Cheat Sheet.md, README.md
=> Helm cheatsheet

Labels&Selectors/README.MD, Labels&Selectors/pod.yml, Labels&Selectors/pod1.yml, Labels&Selectors/svc.yml
Tried creating a labs on how labels and selectors works in kubernetes using service and pod example. Thanks
=> Labels and Selectors

kube101.md
There was extra code syntax quotes.
=> removed code syntax extra quotes

Cheat Sheets/Cloud Cheat Sheet.md
=> Cloud cheatsheet part 1

Cheat Sheets/Cloud Cheat Sheet.md
=> Cloud cheatsheet

Logging101/fluentd-kube.md, Logging101/fluentd.md, README.md
=> Fluentd on Kubernetes

GitOps101/argocd-eks.md, KubeSphere/kubesphere-lab.md, README.md
=> Argocd on EKS 101

bluegreen/README.md, bluegreen/blue.yml, bluegreen/green.yml, bluegreen/svc.yml
In this example we are trying to do a small demo on how blue / green deployment can be achieved using service patch command
=> Blue Green Deployment

ConfigMaps101/what-are-configmaps.md, README.md
=> ConfigMaps 101

README.md
Minor index fixing in `README.md`
From `## Step 2. Run the container` to `## Step 3. Run the container`
=> doc: contribution index fixing

Logging101/filebeat-sidecar.md, Logging101/fluentbit-sidecar.md
=> Fluentbit sidecar
